[package]
name = "nezuo/delta-compress"
# make sure to update docs/intro.MD with the latest version too!
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "shared"

[dependencies]

[dev-dependencies]
Midori = "nezuo/midori@0.1.3"
RemotePacketSizeCounter = "pysephwasntavailable/remotepacketsizecounter@2.4.1"
